services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  RD\ErrorLog\:
    resource: '../Classes/*'

  RD\ErrorLog\EventListener\EmailOnEventOccurredListener:
    tags:
      - name: 'event.listener'
  RD\ErrorLog\EventListener\SlackMessageOnEventOccurredListener:
    tags:
      - name: 'event.listener'
  RD\ErrorLog\EventListener\EmailOnReportEventOccurredListener:
    tags:
      - name: 'event.listener'
  RD\ErrorLog\EventListener\SlackMessageOnReportEventOccurredListener:
    tags:
      - name: 'event.listener'
