services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  RD\ErrorLog\:
    resource: '../Classes/*'

  RD\ErrorLog\Service\ReportService:
    public: true
    autowire: true
    autoconfigure: true

  RD\ErrorLog\Service\ConfigurationService:
    public: true
    autowire: true
    autoconfigure: true

  RD\ErrorLog\Service\CleanService:
    public: true
    autowire: true
    autoconfigure: true

  RD\ErrorLog\Handler\ContentObjectExceptionHandler:
    public: true
    shared: true

  RD\ErrorLog\Handler\DebugExceptionHandler:
    public: true
    shared: true

  RD\ErrorLog\Handler\ProductionExceptionHandler:
    public: true
    shared: true

  RD\ErrorLog\Service\LogWriter:
    public: true
    autowire: true
    autoconfigure: true

  RD\ErrorLog\Task\ServiceManagerTask:
    public: true
    autowire: true
    autoconfigure: true

  RD\ErrorLog\Backend\Controller\AIController:
    public: true
    autowire: true
    autoconfigure: true

  RD\ErrorLog\Backend\Controller\SlackController:
    public: true
    autowire: true
    autoconfigure: true

  RD\ErrorLog\EventListener\EmailOnEventOccurredListener:
    tags:
      - name: 'event.listener'
  RD\ErrorLog\EventListener\SlackMessageOnEventOccurredListener:
    tags:
      - name: 'event.listener'
  RD\ErrorLog\EventListener\EmailOnReportEventOccurredListener:
    tags:
      - name: 'event.listener'
  RD\ErrorLog\EventListener\SlackMessageOnReportEventOccurredListener:
    tags:
      - name: 'event.listener'

  RD\ErrorLog\Queue\Handler\ErrorEmailMessageHandler:
    tags:
      - name: 'messenger.message_handler'

  RD\ErrorLog\Queue\Handler\ErrorSlackMessageHandler:
    tags:
      - name: 'messenger.message_handler'

  RD\ErrorLog\Queue\Handler\ReportEmailMessageHandler:
    tags:
      - name: 'messenger.message_handler'

  RD\ErrorLog\Queue\Handler\ReportSlackMessageHandler:
    tags:
      - name: 'messenger.message_handler'

  RD\ErrorLog\Upgrades\InstallExtension:
    tags:
      - name: install.upgradewizard